"""Worker entrypoint: one job, one issue, run to completion, then exit.

Launched by the scheduler's DockerSocketLauncher with the env vars built by
WorkerJobSpec.to_env(). Reads the issue fresh from GitHub (the scheduler
only passes the issue number, not its body, to keep job specs small),
clones the repo with a token scoped to only this repo, runs the four-stage
pipeline, and reports the outcome back through the shared SQLite store and
onto the issue/PR on GitHub.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import subprocess
import sys
from pathlib import Path

from guppy.common.config import TurnBudgets
from guppy.common.github_client import GitHubClient
from guppy.common.store import Store
from guppy.worker import git_ops
from guppy.worker.pipeline import run_pipeline
from guppy.worker.prompts import PipelineContext

logger = logging.getLogger("guppy.worker")

REPO_DIR = Path("/work/repo")
# Must be on the shared /data volume (mounted into every worker, same as
# the scheduler -- see launcher.py's DATA_MOUNT_PATH), not the worker's own
# ephemeral filesystem: the container is torn down after the job, so
# anything under /work is gone by the time anyone -- including the
# scheduler, which records these paths in the store -- goes looking for it.
ARTIFACTS_ROOT = Path("/data/artifacts")
CONTEXT_FILE_RELATIVE_PATH = ".guppy/context.md"


def _env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise RuntimeError(f"required environment variable {name!r} is not set")
    return value


def _run_setup_commands(commands: list[str], repo_dir: Path) -> None:
    for cmd in commands:
        logger.info("setup: %s", cmd)
        result = subprocess.run(cmd, shell=True, cwd=repo_dir, capture_output=True, text=True)
        if result.returncode != 0:
            # Not fatal -- the implementer/reviewer stages have Bash access
            # and may be able to work around or fix an environment issue.
            # A completely broken setup just wastes their turn budget.
            logger.warning(
                "setup command failed (continuing): %s\nstdout: %s\nstderr: %s",
                cmd, result.stdout, result.stderr,
            )


def _read_context_file(repo_dir: Path) -> str | None:
    path = repo_dir / CONTEXT_FILE_RELATIVE_PATH
    if path.is_file():
        return path.read_text()
    return None


def _pr_body(issue_number: int, issue_body: str) -> str:
    return (
        f"## Automated fix for #{issue_number}\n\n"
        f"{issue_body}\n\n"
        "---\n"
        "> Generated by guppy. Please review carefully before merging, "
        "including the generated tests."
    )


async def _async_main() -> int:
    logging.basicConfig(
        level=os.environ.get("GUPPY_LOG_LEVEL", "INFO"),
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    job_id = _env("GUPPY_JOB_ID")
    repo_slug = _env("GUPPY_REPO_SLUG")
    issue_number = int(_env("GUPPY_ISSUE_NUMBER"))
    base_branch = _env("GUPPY_BASE_BRANCH")
    setup_commands = json.loads(os.environ.get("GUPPY_SETUP_COMMANDS", "[]"))
    turn_budgets = TurnBudgets(
        planner=int(_env("GUPPY_TURN_BUDGET_PLANNER")),
        plan_reviewer=int(_env("GUPPY_TURN_BUDGET_PLAN_REVIEWER")),
        implementer=int(_env("GUPPY_TURN_BUDGET_IMPLEMENTER")),
        code_reviewer=int(_env("GUPPY_TURN_BUDGET_CODE_REVIEWER")),
    )
    github_token = _env("GITHUB_TOKEN")
    sqlite_path = _env("GUPPY_SQLITE_PATH")
    # ANTHROPIC_API_KEY is read directly by the Claude Agent SDK from the
    # environment -- nothing to do with it here.

    store = Store(sqlite_path)
    github = GitHubClient(github_token, repo_slug)

    try:
        store.mark_running(job_id)

        issue = github.get_issue(issue_number)

        logger.info("cloning %s (branch %s)", repo_slug, base_branch)
        git_ops.clone(
            github.clone_url_with_token(), base_branch, REPO_DIR, token=github_token
        )
        git_ops.configure_identity(REPO_DIR)

        if setup_commands:
            _run_setup_commands(setup_commands, REPO_DIR)

        context_file_content = _read_context_file(REPO_DIR)

        ctx = PipelineContext(
            issue_number=issue.number,
            issue_title=issue.title,
            issue_body=issue.body,
            issue_type=issue.validation.issue_type or "unspecified",
            tests_section=issue.validation.tests_section,
            difficulty=issue.validation.difficulty or "difficult",
            context_file_content=context_file_content,
        )

        outcome = await run_pipeline(
            ctx,
            repo_dir=REPO_DIR,
            artifacts_dir=ARTIFACTS_ROOT / job_id,
            turn_budgets=turn_budgets,
            store=store,
            job_id=job_id,
        )

        if outcome.skipped:
            reason = outcome.skip_reason or "the agent could not safely handle this issue"
            logger.info("job %s SKIPped: %s", job_id, reason)
            github.comment(issue_number, f"🤖 The agent could not implement this issue: {reason}")
            store.mark_skipped(job_id, reason)
            return 0

        if outcome.error is not None:
            logger.error("job %s failed: %s", job_id, outcome.error)
            github.comment(
                issue_number,
                f"🤖 The agent ran but did not finish successfully: {outcome.error}. "
                "This has been logged for investigation; no changes were pushed.",
            )
            store.mark_failed(job_id, outcome.error)
            return 1

        if not git_ops.has_changes(REPO_DIR):
            reason = "the agent completed without making any file changes"
            logger.info("job %s: %s", job_id, reason)
            github.comment(issue_number, f"🤖 {reason}. Please review the issue description and try again.")
            store.mark_skipped(job_id, reason)
            return 0

        diff_path = ARTIFACTS_ROOT / job_id / "diff.patch"
        diff_path.write_text(git_ops.full_diff(REPO_DIR, base_branch))
        store.set_artifact(job_id, "diff_artifact_path", str(diff_path))

        slug = git_ops.slugify_title(issue.title)
        branch = f"agent/{issue_number}-{slug}"
        git_ops.create_branch(REPO_DIR, branch)
        git_ops.commit_all(
            REPO_DIR,
            f"fix(#{issue_number}): {issue.title}\n\n"
            f"Automated fix generated by guppy.\nCloses #{issue_number}",
        )
        git_ops.push(REPO_DIR, branch, token=github_token)

        pr_url = github.open_pull_request(
            head_branch=branch,
            base_branch=base_branch,
            title=f"fix(#{issue_number}): {issue.title}",
            body=_pr_body(issue_number, issue.body),
        )
        github.comment(
            issue_number,
            f"🤖 The agent has created a fix: {pr_url}\n\n"
            "Please review the changes (and the generated tests) before merging.",
        )
        store.mark_succeeded(job_id, pr_url)
        logger.info("job %s succeeded: %s", job_id, pr_url)
        return 0

    except Exception as e:
        logger.exception("job %s crashed", job_id)
        try:
            store.mark_failed(job_id, f"worker crashed: {e}")
        except Exception:
            logger.exception("failed to record crash in store")
        try:
            github.comment(
                issue_number,
                f"🤖 The agent crashed while working on this issue: {e}. "
                "This has been logged for investigation; no changes were pushed.",
            )
        except Exception:
            logger.exception("failed to comment on %s#%d about the crash", repo_slug, issue_number)
        return 1


def run() -> None:
    sys.exit(asyncio.run(_async_main()))


if __name__ == "__main__":
    run()
